/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicios25.gui;

import conversores.ConversorCToF;
import conversores.IConversor;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class MainJFrame extends javax.swing.JFrame {
    
    private IConversor conversor;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        conversor = new ConversorCToF();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainjPanel1 = new javax.swing.JPanel();
        inputjTextField1 = new javax.swing.JTextField();
        superiorjLabel1 = new javax.swing.JLabel();
        convertirjButton1 = new javax.swing.JButton();
        inferiorjLabel2 = new javax.swing.JLabel();
        bToAJCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("1 DAW Celsius Converter");
        setResizable(false);

        inputjTextField1.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N

        superiorjLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        superiorjLabel1.setText("Celsius");

        convertirjButton1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        convertirjButton1.setText("Convertir");
        convertirjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirjButton1ActionPerformed(evt);
            }
        });

        inferiorjLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        inferiorjLabel2.setText("Farenheit");

        bToAJCheckBox1.setText("Convertir Farenheit a celsius");
        bToAJCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bToAJCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainjPanel1Layout = new javax.swing.GroupLayout(mainjPanel1);
        mainjPanel1.setLayout(mainjPanel1Layout);
        mainjPanel1Layout.setHorizontalGroup(
            mainjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainjPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainjPanel1Layout.createSequentialGroup()
                        .addComponent(inputjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(superiorjLabel1))
                    .addGroup(mainjPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(convertirjButton1)
                        .addGap(18, 18, 18)
                        .addComponent(inferiorjLabel2))
                    .addComponent(bToAJCheckBox1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainjPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {convertirjButton1, inputjTextField1});

        mainjPanel1Layout.setVerticalGroup(
            mainjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainjPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superiorjLabel1))
                .addGap(18, 18, 18)
                .addGroup(mainjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convertirjButton1)
                    .addComponent(inferiorjLabel2))
                .addGap(18, 18, 18)
                .addComponent(bToAJCheckBox1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainjPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainjPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertirjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirjButton1ActionPerformed
        String input = this.inputjTextField1.getText();
        if (input.matches("[0-9]+(\\.[0-9]+)?")) {
            if (this.bToAJCheckBox1.isSelected()) {
                this.inferiorjLabel2.setText(String.format( "%.2f", conversor.convertAToB(Double.valueOf(this.inputjTextField1.getText()))) + " " + conversor.getASmall());
            }else{
                this.inferiorjLabel2.setText(String.format( "%.2f", conversor.convertBToA(Double.valueOf(this.inputjTextField1.getText()))) + " " + conversor.getBSmall());
            }            
        }else{
            JOptionPane.showMessageDialog(this, "Debe insertar un numero");
            this.inputjTextField1.setText("");
            
        }

    }//GEN-LAST:event_convertirjButton1ActionPerformed

    private void bToAJCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bToAJCheckBox1ActionPerformed
        if (this.bToAJCheckBox1.isSelected()) {
            this.superiorjLabel1.setText("Farenheit");
            this.inferiorjLabel2.setText(conversor);//todo
        }else{
            this.inferiorjLabel2.setText("Farenheit");
            this.superiorjLabel1.setText("Celsius");
        }
    }//GEN-LAST:event_bToAJCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bToAJCheckBox1;
    private javax.swing.JButton convertirjButton1;
    private javax.swing.JLabel inferiorjLabel2;
    private javax.swing.JTextField inputjTextField1;
    private javax.swing.JPanel mainjPanel1;
    private javax.swing.JLabel superiorjLabel1;
    // End of variables declaration//GEN-END:variables
}
